{% set name = "paramak" %}

package:
  name: "{{ name|lower }}"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python {{ python }}
    - setuptools>=46.4.0
    - setuptools_scm>=6.3.1
  run:
    - python {{ python }}
    - cadquery {{ cadquery }}
    - mpmath
    - plasmaboundaries >=0.1.8
    - plotly
    - brep_part_finder >=0.5.0 # [not win]
    - brep_to_h5m >=0.4.0 # [not win]
    - moab * nompi_tempest_*
    # - jupyter-cadquery not available on conda

test:
  imports:
    - paramak
    - paramak.parametric_components
    - paramak.parametric_reactors
    - paramak.parametric_shapes
  requires:
    - pytest
    - dagmc_h5m_file_inspector  # [not win]
  source_files:
    - tests/tests_units
    - examples/
    - tests/tests_h5m/  # [not win]
    # - tests/tests_examples/  # TODO include if cadquery_jupyter gets a conda install
  commands:
    - pytest -v tests/tests_h5m  # [not win]
    - pytest -v tests/tests_units
    # - pytest -v tests/tests_show  # TODO include if cadquery_jupyter gets a conda install
    # - pytest -v tests/tests_examples  # TODO include if cadquery_jupyter gets a conda install

about:
  home: "https://github.com/fusion-energy/paramak"
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "Create 3D fusion reactor CAD models based on input parameters"
  doc_url: https://paramak.readthedocs.io/
  dev_url: https://github.com/fusion-energy/paramak
  summary: Paramak - parameter driven fusion reactor model creation

extra:
  recipe-maintainers:
    - shimwell
