# This yml file will trigger a Github Action on release creation.
# This Action will build and upload a Docker image to GHCR
# https://github.com/marketplace/actions/publish-docker

name: docker-publish-release

on:
  # allows us to run workflows manually
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build_and_push_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build and push dependencies Docker image CQ=master
        uses: docker/build-push-action@v2
        with:
          push: true
          target: dependencies
          tags: ghcr.io/fusion-energy/paramak_cq_master:dependencies
          build-args: |
            cq_version=master
            paramak_version=${{ github.ref_name }}

      - name: Build and push dependencies Docker image CQ=2.1
        uses: docker/build-push-action@v2
        with:
          push: true
          target: dependencies
          tags: ghcr.io/fusion-energy/paramak:dependencies
          build-args: |
            cq_version=2.1
            paramak_version=${{ github.ref_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push final Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fusion-energy/paramak
          build-args: |
            cq_version=2.1
